//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDW_MAIN                        41
#define IDW_ABOUT                       42
#define IDW_VIEW_TOOLBAR                43
#define IDW_VIEW_STATUSBAR              44
#define IDW_READY                       45
#define IDW_INDICATOR_CAPS              46
#define IDW_INDICATOR_NUM               47
#define IDW_INDICATOR_SCRL              48
#define IDW_MENUBAR                     49
#define IDW_TOOLBAR                     50
#define IDW_QUIT                        51
#define IDW_MDI_CASCADE                 52
#define IDW_MDI_TILE                    53
#define IDW_MDI_ARRANGE                 54
#define IDW_MDI_CLOSEALL                55
#define IDW_FIRSTCHILD                  56
#define IDW_CHILD2                      57
#define IDW_CHILD3                      58
#define IDW_CHILD4                      59
#define IDW_CHILD5                      60
#define IDW_CHILD6                      61
#define IDW_CHILD7                      62
#define IDW_CHILD8                      63
#define IDW_CHILD9                      64
#define IDW_CHILD10                     65
#define IDW_FILE_MRU_FILE1              66
#define IDW_FILE_MRU_FILE2              67
#define IDW_FILE_MRU_FILE3              68
#define IDW_FILE_MRU_FILE4              69
#define IDW_FILE_MRU_FILE5              70
#define IDW_FILE_MRU_FILE6              71
#define IDW_FILE_MRU_FILE7              72
#define IDW_FILE_MRU_FILE8              73
#define IDW_FILE_MRU_FILE9              74
#define IDW_FILE_MRU_FILE10             75
#define IDW_FILE_MRU_FILE11             76
#define IDW_FILE_MRU_FILE12             77
#define IDW_FILE_MRU_FILE13             78
#define IDW_FILE_MRU_FILE14             79
#define IDW_FILE_MRU_FILE15             80
#define IDW_FILE_MRU_FILE16             81
#define IDW_SPLITH                      82
#define IDW_SPLITV                      83
#define IDW_TRACK4WAY                   84
#define IDW_SDBOTTOM                    85
#define IDW_SDCENTER                    86
#define IDW_SDLEFT                      87
#define IDW_SDMIDDLE                    88
#define IDW_SDRIGHT                     89
#define IDW_SDTOP                       90
#define IDW_PRINTPREVIEW                91
#define IDW_PREVIEWPRINT                92
#define IDW_PREVIEWSETUP                93
#define IDW_PREVIEWPREV                 94
#define IDW_PREVIEWNEXT                 95
#define IDW_PREVIEWCLOSE                96
#define IDW_PREVIEWPANE                 97
#define IDM_FILE_NEW                    121
#define IDM_FILE_OPEN                   122
#define IDM_FILE_SAVE                   123
#define IDM_FILE_SAVEAS                 124
#define IDM_FILE_PRINT                  125
#define IDM_FILE_CLOSE                  126
#define IDM_FILE_EXIT                   127
#define IDM_EDIT_UNDO                   130
#define IDM_EDIT_REDO                   131
#define IDM_EDIT_CUT                    132
#define IDM_EDIT_COPY                   133
#define IDM_EDIT_PASTE                  134
#define IDM_EDIT_DELETE                 135
#define IDM_HELP_ABOUT                  140
#define IDB_PNG1                        174
#define IDB_PNG2                        175
#define IDB_PNG3                        176
#define IDB_PNG4                        177
#define IDB_PNG5                        178
#define IDB_PNG6                        179
#define IDB_PNG7                        180
#define IDB_BITMAP17                    181
#define IDB_BITMAP18                    182
#define IDB_BITMAP19                    183
#define IDB_BITMAP20                    184
#define IDB_BITMAP21                    185
#define IDB_BITMAP22                    186
#define IDB_BITMAP23                    187
#define IDB_BITMAP24                    188
#define IDB_BITMAP25                    189
#define IDB_BITMAP26                    190
#define IDB_BITMAP27                    191
#define IDB_BITMAP28                    192
#define IDB_BITMAP29                    193
#define IDB_BITMAP30                    194
#define IDB_BITMAP31                    195
#define IDB_BITMAP32                    196
#define IDR_MENU1                       500
#define IDR_MENU2                       501
#define IDR_TREELISTMENU                502
#define IDR_TREELIST_MENU               503
#define IDB_BITMAP1                     510
#define IDB_BITMAP2                     511
#define IDB_BITMAP3                     512
#define IDB_BITMAP4                     513
#define IDB_BITMAP5                     514
#define IDB_BITMAP6                     515
#define IDB_BITMAP7                     516
#define IDB_BITMAP8                     517
#define IDB_BITMAP9                     518
#define IDB_BITMAP10                    519
#define IDB_BITMAP11                    520
#define IDB_BITMAP12                    521
#define IDB_BITMAP13                    522
#define IDB_BITMAP14                    523
#define IDB_BITMAP15                    524
#define IDB_BITMAP16                    525
#define IDB_TOOLBAR                     526
#define IDB_FILEVIEW                    527
#define IDI_FILEVIEW                    528
#define IDI_ICON1                       529
#define IDC_ZOOMIN                      600
#define IDC_ZOOMOUT                     601
#define IDC_OPENHAND                    602
#define IDC_CLOSEDHAND                  603
#define IDC_CURSOR3                     604
#define IDS_STRING42                    700
#define IDS_STRING49                    701
#define IDS_STRING16012                 702
#define IDS_STRING16022                 703
#define IDS_STRING16023                 704
#define IDS_STRING16032                 705
#define IDS_STRING16052                 706
#define IDS_STRING16062                 707
#define IDS_STRING61729                 708
#define IDM_PEN_RED                     1000
#define IDM_PEN_BLUE                    1001
#define IDM_PEN_GREEN                   1002
#define IDM_PEN_BLACK                   1003
#define IDC_CUSTOMER_FATHERNAME         1016
#define IDC_BIRTHDATE                   1017
#define IDC_EDIT2                       1018
#define IDC_IBANNO                      1018
#define IDC_DATETIMEPICKER2             1020
#define IDC_DATETIMEPICKER1             1021
#define IDC_CMD_VIEW_CARD               1032
#define IDC_CMD_VIEW_REPORT             1033
#define ID_MAINLISTVIEWMENU_EKLE        1100
#define ID_MAINLISTVIEWMENU_KAY         1101
#define ID_MAINLISTVIEWMENU_SIL         1102
#define ID_MAINLISTVIEWMENU_YENIM32782  1104
#define ID_MAINLISTVIEWMENU_32786       1105
#define ID_MAINLISTVIEWMENU_32787       1106
#define ID_MAINLISTVIEWMENU_D32788      1107
#define ID_FILE_VERITABAN32794          1109
#define ID_MAINLISTVIEWMENU_KAY32796    1110
#define ID_MAINLISTVIEWMENU_WEBADRESINEGIT 1111
#define ID_MAINLISTVIEWMENU_G32799      1112
#define ID_G32800                       1113
#define ID_G32801                       1114
#define ID_TREELISTVIEWMENU_D32804      1115
#define ID_TREELISTVIEWMENU_SIL         1116
#define ID_TREELISTVIEWMENU_G32806      1117
#define ID_TREELISTVIEWMENU_SAT32807    1118
#define ID_TREELISTVIEWMENU_SAT32808    1119
#define ID_TREELISTVIEWMENU_BEKLEMEDE   1120
#define ID_TREELISTVIEWMENU_DURUMUBELIRSIZ 1121
#define ID_TREELISTVIEWMENU_SAT32811    1122
#define ID_TREELISTVIEWMENU_BASK32813   1123
#define ID_MAINLISTVIEWMENU_BULUTAG32814 1124
#define ID_TREELISTVIEWMENU_FONT        1125
#define ID_TREELISTVIEWMENU_BA32821     1126
#define ID_TREELISTVIEWMENU_SAT32823    1127
#define ID_TREELISTVIEWMENU_CAYMAAK32825 1128
#define ID_TREELISTVIEWMENU_KIRAL32827  1129
#define ID_TREELISTVIEWMENU_KIRAKONTRATOSU 1130
#define ID_TREELISTVIEWMENU_TEKLIFFORMU 1131
#define ID_TREELISTVIEWMENU_YERG32833   1132
#define ID_TREELISTVIEWMENU_HAY32835    1133
#define ID_TREELISTVIEWMENU_TEKLIFVER   1134
#define ID_CMD_ADD_CUSTOMER             1200
#define ID_CMD_EDIT_CUSTOMER            1201
#define ID_CMD_VIEW_CUSTOMER            1202
#define ID_CMD_DELETE_CUSTOMER          1203
#define ID_CMD_ADD_PROPERTY             1204
#define ID_CMD_EDIT_PROPERTY            1205
#define ID_CMD_VIEW_PROPERTY            1206
#define ID_CMD_DELETE_PROPERTY          1207
#define IDD_HOME_DIALOG                 2000
#define ID_EDIT_HOME_CODE               2001
#define ID_EDIT_ADRES                   2002
#define ID_EDIT_LOKASYON                2003
#define ID_EDIT_ODASAYISI               2004
#define ID_EDIT_NETM2                   2005
#define ID_EDIT_BRUTM2                  2006
#define ID_EDIT_KAT                     2007
#define ID_EDIT_BINAYASI                2008
#define ID_EDIT_FIYAT                   2009
#define ID_EDIT_DURUM                   2010
#define ID_COMBO_ISITMA                 2011
#define ID_CHECK_BALKON                 2012
#define ID_CHECK_OTOPARK                2013
#define ID_STATIC_HOME_CODE             2014
#define IDC_EDIT_CARI_KOD               2015
#define ID_STATIC_ADRES                 2016
#define ID_STATIC_LOKASYON              2017
#define ID_STATIC_ODASAYISI             2018
#define ID_STATIC_NETM2                 2019
#define ID_STATIC_BRUTM2                2020
#define ID_STATIC_KAT                   2021
#define ID_STATIC_BINAYASI              2022
#define ID_STATIC_ISITMA                2023
#define ID_STATIC_BALKON                2024
#define ID_STATIC_FIYAT                 2025
#define ID_STATIC_DURUM                 2026
#define ID_STATIC_OTOPARK               2027
#define IDC_EDIT_ILAN_NO                2030
#define IDC_EDIT_KAT_SAYISI             2031
#define IDC_EDIT_BANYO_SAYISI           2032
#define IDC_COMBO_MUTFAK                2033
#define IDC_COMBO_TAPU_DURUMU           2034
#define IDC_COMBO_KIMDEN                2035
#define IDC_EDIT_AIDAT                  2036
#define IDC_EDIT_TEKLIFLER              2037
#define IDC_CHECK_ESYALI                2038
#define IDC_CHECK_KREDIYE_UYGUN         2039
#define IDC_BTN_LOAD_CSV                2040
#define IDC_TAB_HOME                    2041
#define IDC_BTN_LOADTXT                 2042
#define IDC_EDIT_LISTING_DATE           2043
#define IDC_EDIT_PROPERTY_TYPE          2044
#define IDC_COMBO_PROPERTY_TYPE         2044
#define IDC_EDIT_CITY                   2045
#define IDC_EDIT_DISTRICT               2046
#define IDC_EDIT_NEIGHBORHOOD           2047
#define IDC_EDIT_SITE_ADI               2048
#define IDC_EDIT_PRICE_PER_M2           2049
#define IDC_EDIT_URL                    2050
#define IDC_EDIT_NOTE_GENERAL           2051
#define IDC_EDIT_NOTE_INTERNAL          2052
#define IDC_EDIT_PURCHASE_DATE          2053
#define IDC_EDIT_PURCHASE_PRICE         2054
#define IDC_EDIT_SALE_DATE              2055
#define IDC_EDIT_SALE_PRICE             2056
#define IDC_EDIT_ENERGY_CLASS           2057
#define IDC_EDIT_GEO_LAT                2058
#define IDC_EDIT_GEO_LON                2059
#define IDC_EDIT_PHOTO_COUNT            2060
#define IDC_EDIT_UPDATED_AT             2061
#define IDC_COMBO_BALCONY               2062
#define IDC_COMBO_ELEVATOR              2063
#define IDC_COMBO_PARKING               2064
#define IDC_COMBO_ESYALI                2065
#define IDC_COMBO_USAGE_STATUS          2066
#define IDC_COMBO_INSITE                2067
#define IDC_COMBO_CREDIT_ELIGIBLE       2068
#define IDC_COMBO_DEED_STATUS           2069
#define IDC_COMBO_SELLER_TYPE           2070
#define IDC_COMBO_SWAP                  2071
#define IDC_COMBO_CURRENCY              2072
#define IDC_COMBO_WEBSITE               2073
#define IDC_COMBO_STATUS                2074
#define ID_BTN_SAVE                     2075
#define ID_BTN_CANCEL                   2076
#define IDC_BTN_OPEN_URL                2077
#define IDC_BTN_GEOLOCATE               2078
#define IDC_BTN_LOADURL                 2079
#define IDC_BTN_LOADURLJSON             2080
#define IDC_EDIT_COOKIE                 2081
#define IDC_BTN_PASTCOOKIE              2082
#define IDC_BTN_LOADHTML                2083
#define IDC_BTN_LOAD_CLIPBOARD          2084
#define IDC_EDIT_ADA                    2085
#define IDC_EDIT_PARSEL                 2086
#define IDC_EDIT_PAFTA                  2087
#define IDC_EDIT_YETKI_BASLANGIC        2088
#define IDC_EDIT_YETKI_BITIS            2089
#define IDD_LAND_DIALOG                 3000
#define IDC_EDIT_LAND_CODE              3001
#define IDC_EDIT_LAND_ADRES             3002
#define IDC_EDIT_LAND_LOKASYON          3003
#define IDC_EDIT_LAND_ADA               3004
#define IDC_EDIT_LAND_PARSEL            3005
#define IDC_EDIT_LAND_PAFTA             3006
#define IDC_EDIT_LAND_M2                3007
#define IDC_EDIT_LAND_IMAR              3008
#define IDC_EDIT_LAND_FIYAT             3009
#define IDC_EDIT_LAND_TEKLIF            3010
#define IDC_EDIT_LAND_DURUM             3011
#define IDC_LAND_CARI_KOD               3012
#define IDC_LAND_LISTING_NO             3013
#define IDC_LAND_LISTING_DATE           3014
#define IDC_LAND_PROPERTY_TYPE          3015
#define IDC_LAND_SELLER_TYPE            3016
#define IDC_LAND_CREDIT_ELIGIBLE        3017
#define IDC_LAND_SWAP                   3018
#define IDC_LAND_PRICE_PER_M2           3019
#define IDC_LAND_DEED_STATUS            3020
#define IDC_LAND_KAKS                   3021
#define IDC_LAND_GABARI                 3022
#define IDC_LAND_CURRENCY               3023
#define IDC_LAND_AUTH_START             3024
#define IDC_LAND_AUTH_END               3025

// Land - Özellikler (Attributes JSON)
#define IDC_LAND_CHK_ELEKTRIK           3030
#define IDC_LAND_CHK_SANAYI_ELEK        3031
#define IDC_LAND_CHK_SU                 3032
#define IDC_LAND_CHK_DOGALGAZ           3033
#define IDC_LAND_CHK_KANAL              3034
#define IDC_LAND_CHK_ARITMA             3035
#define IDC_LAND_CHK_ZEMIN              3036
#define IDC_LAND_CHK_YOL_ACILMIS        3037
#define IDC_LAND_CHK_YOL_ACILMAMIS      3038
#define IDC_LAND_CHK_YOL_YOK            3039
#define IDC_LAND_CHK_TELEFON            3040
#define IDC_LAND_CHK_SONDAJ             3041

#define IDC_LAND_CHK_ANA_YOL            3042
#define IDC_LAND_CHK_TOPLU_ULASIM       3043
#define IDC_LAND_CHK_DENIZE_SIFIR       3044
#define IDC_LAND_CHK_DENIZE_YAKIN       3045
#define IDC_LAND_CHK_HAVAALANI          3046

#define IDC_LAND_CHK_IFRAZLI            3047
#define IDC_LAND_CHK_PARSELLI           3048
#define IDC_LAND_CHK_PROJELI            3049
#define IDC_LAND_CHK_KOSE               3050

#define IDC_LAND_CHK_SEHIR              3051
#define IDC_LAND_CHK_GOL                3052
#define IDC_LAND_CHK_DENIZ              3053
#define IDC_LAND_CHK_DOGA               3054
#define IDC_LAND_CHK_BOGAZ              3055

#define IDD_FLD_DIALOG                  4000
#define IDC_FLD_CARI_KOD                4001
#define IDC_SAHI_URL                    4001
#define IDC_FLD_CODE                    4002
#define IDC_SAHI_DOWNLOAD               4002
#define IDC_FLD_LISTING_NO              4003
#define IDC_SAHI_LOG                    4003
#define IDC_SAHI_CONTACT_NAME           4004
#define IDC_FLD_ADDRESS                 4004
#define IDC_SAHI_CONTACT_PHONE          4005
#define IDC_FLD_LOCATION                4005
#define IDC_SAHI_PASTE_CLIP             4006
#define IDC_FLD_AREA_M2                 4006
#define IDC_FLD_ACCESS                  4007
#define IDC_FLD_ADA                     4008
#define IDC_FLD_PARSEL                  4009
#define IDC_FLD_PAFTA                   4010
#define IDC_FLD_PRICE                   4011
#define IDC_FLD_PRICE_PER_M2            4012
#define IDC_FLD_TEKLIFLER               4013
#define IDC_FLD_DURUM                   4014
#define IDC_FLD_TOPRAK                  4015
#define IDC_FLD_SULAMA                  4016
#define IDC_FLD_DEED_STATUS             4017
#define IDC_FLD_IMAR                    4018
#define IDC_FLD_KAKS                    4019
#define IDC_FLD_GABARI                  4020
#define IDC_FLD_SELLER                  4021
#define IDC_FLD_SWAP                    4022
#define IDC_FLD_CREDIT                  4023
#define IDC_FLD_BTN_GETCLIPBOARD        4024
#define IDC_FLD_ILAN_DATE               4025
#define IDC_FLD_LOAD_KML                4026
#define IDC_OPEN_IN_EARTH               4027
#define IDC_FLD_MERGE                   4028
#define IDC_EDIT_FIELD_LISTING_NO       4029
#define IDC_EDIT_FIELD_ULASIM           4030
#define IDC_EDIT_FIELD_PAFTA            4031
#define IDC_COMBO_FIELD_DEED_STATUS     4032
#define IDC_COMBO_FIELD_CREDIT          4033
#define IDC_EDIT_FIELD_PRICE_PER_M2     4034
#define IDC_COMBO_FIELD_SWAP            4035
#define IDC_COMBO_FIELD_SELLER          4036
#define IDC_EDIT_FIELD_ADA              4037
#define IDC_EDIT_FIELD_PARSEL           4038
#define IDC_COMBO_FIELD_IMAR            4039
#define IDC_EDIT_FIELD_FIYAT            4040
#define IDC_EDIT_FIELD_TEKLIFLER        4041
#define IDC_EDIT_FIELD_DURUM            4042
#define IDC_COMBO_FIELD_KAKS            4043
#define IDC_FLD_BTN_SAVE                4050
#define IDC_FLD_BTN_CANCEL              4051
#define IDD_VINEYARD_DIALOG             5000
#define IDC_SYNC_PROGRESS_BAR           5001
#define IDC_LBL_STATUS                  5002
#define IDC_EDIT_VINEYARD_LOKASYON      5003
#define IDC_EDIT_VINEYARD_M2            5004
#define IDC_EDIT_VINEYARD_AGAC          5005
#define IDC_COMBO_VINEYARD_URUN         5006
#define IDC_COMBO_VINEYARD_SULAMA       5007
#define IDC_EDIT_VINEYARD_FIYAT         5008
#define IDC_EDIT_VINEYARD_TEKLIFLER     5009
#define IDC_EDIT_VINEYARD_DURUM         5010
#define IDD_VILLA_DIALOG                6000
#define IDD_VILLA_PAGE_GENEL           8301
#define IDD_VILLA_PAGE_NOTLAR          8302
#define IDD_VILLA_PAGE_OZELLIKLER      8303
#define IDC_EDIT_VILLA_CODE             6001
#define IDC_EDIT_VILLA_ADRES            6002
#define IDC_EDIT_VILLA_LOKASYON         6003
#define IDC_EDIT_VILLA_NETM2            6004
#define IDC_EDIT_VILLA_BRUTM2           6005
#define IDC_EDIT_VILLA_ODA              6006
#define IDC_EDIT_VILLA_KAT              6007
#define IDC_COMBO_VILLA_HAVUZ           6008
#define IDC_COMBO_VILLA_BAHCE           6009
#define IDC_COMBO_VILLA_GARAJ           6010
#define IDC_EDIT_VILLA_FIYAT            6011
#define IDC_EDIT_VILLA_TEKLIFLER        6012
#define IDC_EDIT_VILLA_DURUM            6013
#define IDC_EDIT_VILLA_CARI_KOD          6014
#define IDC_EDIT_VILLA_LISTING_NO        6015
#define IDC_DTP_VILLA_LISTING_DATE       6016
#define IDC_EDIT_VILLA_WEBSITE_NAME      6017
#define IDC_EDIT_VILLA_LISTING_URL       6018
#define IDC_DTP_VILLA_YETKI_BAS          6019
#define IDC_DTP_VILLA_YETKI_BIT          6020
#define IDC_EDIT_VILLA_ADA               6021
#define IDC_EDIT_VILLA_PARSEL            6022
#define IDC_EDIT_VILLA_PAFTA             6023
#define IDC_COMBO_VILLA_PROPERTY_TYPE    6024
#define IDC_EDIT_VILLA_ACIKALAN          6025
#define IDC_COMBO_VILLA_BUILDING_AGE     6026
#define IDC_COMBO_VILLA_HEATING          6027
#define IDC_EDIT_VILLA_BATHROOM          6028
#define IDC_COMBO_VILLA_KITCHEN          6029
#define IDC_COMBO_VILLA_PARKING          6030
#define IDC_COMBO_VILLA_FURNISHED        6031

// ---------------------------------------------------------------------------
// Backward-compatible aliases (older code/schema names)
// ---------------------------------------------------------------------------
// Some modules still reference these legacy identifier names.
// Keep them as aliases so we don't break existing code.
#define IDC_COMBO_VILLA_OTOPARK          IDC_COMBO_VILLA_PARKING
#define IDC_COMBO_VILLA_ESYALI           IDC_COMBO_VILLA_FURNISHED
#define IDC_COMBO_VILLA_USAGE            6032
#define IDC_COMBO_VILLA_INSITE           6033
#define IDC_EDIT_VILLA_SITENAME          6034
#define IDC_EDIT_VILLA_DUES              6035
#define IDC_COMBO_VILLA_CREDIT           6036
#define IDC_EDIT_VILLA_DEEDSTATUS        6037
#define IDC_COMBO_VILLA_SELLER_TYPE      6038
#define IDC_COMBO_VILLA_SWAP             6039
#define IDC_EDIT_VILLA_SELLER_NAME       6040
#define IDC_EDIT_VILLA_SELLER_PHONE      6041
#define IDC_EDIT_VILLA_DESCRIPTION       6042
#define IDC_COMBO_VILLA_CURRENCY         6043
#define IDC_TAB_VILLA                   6044
#define IDC_TAB_VILLA_FEATURES          6045
#define IDD_SYNC_PROGRESS               6842
#define IDC_EDIT_VINEYARD_CODE          6843
#define IDC_EDIT_VINEYARD_ADRES         6844
#define IDC_SYNC_STATUS_TEXT            6845
#define IDD_APP_LIST_DLG                6900
#define IDC_APP_LIST_VIEW               6901
#define IDD_COMMERCIAL_DIALOG           7000
#define IDC_EDIT_COMM_CODE              7001
#define IDC_EDIT_COMM_ADRES             7002
#define IDC_EDIT_COMM_LOKASYON          7003
#define IDC_EDIT_COMM_ALAN              7004
#define IDC_EDIT_COMM_KAT               7005
#define IDC_COMBO_COMM_CEPHE            7006
#define IDC_COMBO_COMM_KULLANIM         7007
#define IDC_EDIT_COMM_FIYAT             7008
#define IDC_EDIT_COMM_TEKLIFLER         7009
#define IDC_EDIT_COMM_DURUM             7010
#define IDD_CAR_DIALOG                  7100
#define IDC_TAB_CAR                     7101
#define IDC_EDIT_CAR_CODE               7110
#define IDC_EDIT_CAR_TITLE              7111
#define IDC_EDIT_CAR_BRAND              7112
#define IDC_EDIT_CAR_SERIES             7113
#define IDC_EDIT_CAR_MODEL              7114
#define IDC_EDIT_CAR_YEAR               7115
#define IDC_EDIT_CAR_KM                 7116
#define IDC_EDIT_CAR_PRICE              7117
#define IDC_EDIT_CAR_CURRENCY           7118
#define IDC_EDIT_CAR_FUEL               7119
#define IDC_EDIT_CAR_GEAR               7120
#define IDC_EDIT_CAR_ENGVOL             7121
#define IDC_EDIT_CAR_ENGPOWER           7122
#define IDC_EDIT_CAR_DRIVE              7123
#define IDC_EDIT_CAR_BODY               7124
#define IDC_EDIT_CAR_COLOR              7125
#define IDC_EDIT_CAR_DAMAGE             7126
#define IDC_EDIT_CAR_WARRANTY           7127
#define IDC_EDIT_CAR_PLATE              7128
#define IDC_EDIT_CAR_LISTINGNO          7129
#define IDC_EDIT_CAR_LISTINGDATE        7130
#define IDC_EDIT_CAR_WEBSITE            7131
#define IDC_EDIT_CAR_URL                7132
#define IDC_EDIT_CAR_STATUS             7133
#define IDC_EDIT_CAR_DURUM              7134
#define IDC_EDIT_CAR_NOTES              7135
#define IDC_BTN_CAR_PARSE               7136
#define IDC_EDIT_CAR_CITY               7137
#define IDC_EDIT_CAR_DISTRICT           7138
#define IDC_EDIT_CAR_NEIGHBOR           7139
#define IDC_EDIT_CAR_SELLERNAME         7140
#define IDC_EDIT_CAR_SELLERPHONE        7141
#define IDC_EDIT_CAR_CONDITION          7142
#define IDC_EDIT_CAR_FROMWHO            7143
#define IDC_EDIT_CAR_SWAP               7144
#define IDC_EDIT_CAR_DESC               7145
#define IDC_EDIT_CAR_SAFETY             7146
#define IDC_EDIT_CAR_INTERIOR           7147
#define IDC_EDIT_CAR_EXTERIOR           7148
#define IDC_EDIT_CAR_MEDIA              7149
#define IDC_CAR_PAINT_CANVAS            7150
#define IDC_CAR_PAINT_LIST              7151
#define IDC_BTN_CAR_PAINT_CLEAR         7152
#define IDC_EDIT_CAR_PAINTINFO          7153
#define IDD_PROP_SELECT_DLG             7450
#define IDC_PROP_SEL_LIST               7451
#define IDC_PROP_SEL_COMBO              7452
#define IDD_CUSTOMER_DIALOG             8000
#define IDD_CUSTOMER_DIALOG1            8001
#define IDC_EDIT_ADSOYAD                8002
#define IDC_EDIT_TELEFON                8003
#define IDC_EDIT_TELEFON2               8004
#define IDC_EDIT_EMAIL                  8005
#define IDC_EDIT_SEHIR                  8006
#define IDC_EDIT_ILCE                   8007
#define IDC_EDIT_TCKN                   8008
#define IDC_EDIT_VERGINO                8009
#define IDC_EDIT_KAYITTARIHI            8010
#define IDC_COMBO_MUSTERI_TIPI          8011
#define IDC_EDIT_NOTLAR                 8012
#define IDC_STATIC_CUSTOMER_INFO        8013
#define IDC_LOAD_CSV                    8014
#define IDC_EDIT_ADRES                  8015
#define IDC_COMBO_DURUM                 8016
#define IDD_CUSTOMER_LIST_DIALOG        8100
#define IDC_CUST_LIST_SEARCH            8101
#define IDC_CUST_LIST_VIEW              8102
#define IDC_CUST_LIST_BTN_SELECT        8103
#define IDC_CUST_LIST_BTN_CANCEL        8104
#define IDC_CUST_LIST_BTN_SEARCH        8105
#define IDD_PAGE_GENEL                  8201
#define IDD_PAGE_TEKNIK                 8202
#define IDD_PAGE_ILAN                   8203
#define IDD_PAGE_NOTLAR                 8204
#define IDD_PAGE_ACIKLAMA               8205
#define IDD_PAGE_DONANIM                8206
#define IDD_PAGE_EKSPERTIZ              8207
#define IDD_OFFER_DIALOG                8500
#define IDC_OFFER_PROPERTY_INFO         8501
#define IDC_OFFER_CUST_NAME             8502
#define IDC_OFFER_BTN_SELECT_CUST       8503
#define IDC_OFFER_CUST_TC               8504
#define IDC_OFFER_CUST_TEL              8505
#define IDC_OFFER_PRICE                 8506
#define IDC_OFFER_CURRENCY              8507
#define IDC_OFFER_DEPOSIT               8508
#define IDC_OFFER_PAYMENT_TYPE          8509
#define IDC_OFFER_VALIDITY_DATE         8510
#define IDC_OFFER_STATUS                8511
#define IDC_OFFER_NOTES                 8512
#define IDC_OFFER_BTN_SAVE              8513
#define IDC_OFFER_BTN_CANCEL            8514
#define IDD_OFFER_LIST_DIALOG           8600
#define IDC_OFFER_LIST_VIEW             8601
#define IDC_OFFER_LIST_BTN_CLOSE        8602
#define IDD_PREVIEW_DLG                 9000
#define IDC_PREVIEW_CANVAS              9001
#define IDC_PREVIEW_PRINT               9002
#define IDC_PREVIEW_ZOOMIN              9003
#define IDC_PREVIEW_ZOOMOUT             9004
#define IDC_PREVIEW_BACK                9005
#define IDC_CUSTOM_CANVAS               9006
#define IDD_TREELISTVIEWDLG             9100
#define IDC_TREELISTVIEWCTRL            9101
#define IDD_COLUMN_MANAGER              9200
#define IDC_COL_LIST                    9201
#define IDC_APPLY                       9202
#define IDC_CANCEL                      9203
#define IDC_CUSTOM1                     9300
#define IDC_LIST1                       9301
#define IDC_BUTTON1                     9302
#define IDC_GET_CLIBBOARD               9303
#define IDC_BACKTOLISTVIEW              9304
#define IDC_EDIT1                       9305
#define ID_BTN_PREV_PAGE                9306
#define ID_BTN_NEXT_PAGE                9307
#define IDC_COMBO1                      9308
#define IDC_BANKNAME                    9308
#define IDD_COMPANY_DIALOG              9500
#define IDC_COMP_NAME                   9501
#define IDC_COMP_OWNER                  9502
#define IDC_COMP_TTBS                   9503
#define IDC_COMP_TAX_OFF                9504
#define IDC_COMP_TAX_NO                 9505
#define IDC_COMP_MERSIS                 9506
#define IDC_COMP_TEL_FIX                9510
#define IDC_COMP_TEL_MOB                9511
#define IDC_COMP_EMAIL                  9512
#define IDC_COMP_WEB                    9513
#define IDC_COMP_ADDRESS                9514
#define IDC_COMP_LOGO_PATH              9520
#define IDC_COMP_BTN_LOGO               9521
#define IDC_COMP_ABOUT                  9522
#define IDC_COMP_IMG_PREVIEW            9523
#define cmdTabHome                      10000
#define cmdTabHome_LabelTitle_RESID     10001
#define cmdTabText                      10010
#define cmdTabText_LabelTitle_RESID     10011
#define cmdGroup1                       11000
#define cmdGroup1_LabelTitle_RESID      11001
#define cmdGroup2                       11010
#define cmdGroup2_LabelTitle_RESID      11011
#define cmdGroup2_SmallImages_RESID     11012
#define cmdDropDownColorPickerGroup     11020
#define cmdDropDownColorPickerGroup_LabelTitle_RESID 11021
#define cmdGroupRichFont                11030
#define cmdGroupRichFont_LabelTitle_RESID 11031
#define IDC_CMD_NEW                     12000
#define IDC_CMD_NEW_LabelTitle_RESID    12001
#define IDC_CMD_NEW_LargeImages_RESID   12002
#define IDC_CMD_OPEN                    12010
#define IDC_CMD_OPEN_LabelTitle_RESID   12011
#define IDC_CMD_OPEN_LargeImages_RESID  12012
#define IDC_CMD_SAVE                    12020
#define IDC_CMD_SAVE_LabelTitle_RESID   12021
#define IDC_CMD_SAVE_LargeImages_RESID  12022
#define IDC_CMD_SAVE_AS                 12030
#define IDC_CMD_SAVE_AS_LabelTitle_RESID 12031
#define IDC_CMD_SAVE_AS_LargeImages_RESID 12032
#define IDC_CMD_PRINT                   12040
#define IDC_CMD_PRINT_LabelTitle_RESID  12041
#define IDC_CMD_PRINT_LargeImages_RESID 12042
#define IDC_CMD_COPY                    12050
#define IDC_CMD_COPY_LabelTitle_RESID   12051
#define IDC_CMD_COPY_SmallImages_RESID  12052
#define IDC_CMD_CUT                     12060
#define IDC_CMD_CUT_LabelTitle_RESID    12061
#define IDC_CMD_CUT_SmallImages_RESID   12062
#define IDC_CMD_PASTE                   12070
#define IDC_CMD_PASTE_LabelTitle_RESID  12071
#define IDC_CMD_PASTE_LargeImages_RESID 12072
#define IDC_CMD_ABOUT                   12080
#define IDC_CMD_ABOUT_LabelTitle_RESID  12081
#define IDC_CMD_ABOUT_LargeImages_RESID 12082
#define IDC_CMD_EXIT                    12090
#define IDC_CMD_EXIT_LabelTitle_RESID   12091
#define IDC_CMD_EXIT_LargeImages_RESID  12092
#define IDM_COMPANY_SETTINGS            12600
#define IDM_VIEW_STARTUP_SYNC_PROGRESS  12610
#define IDC_PEN_COLOR                   13000
#define IDC_PEN_COLOR_LargeImages_RESID 13001
#define IDC_PEN_COLOR_LabelTitle_RESID  13002
#define IDC_PEN_COLOR_LabelDescription_RESID 13003
#define IDC_RICHFONT                    14000
#define IDC_RICHFONT_Keytip_RESID       14001
#define IDC_MRUMENU                     14010
#define IDC_MRULIST                     14020
#define IDC_QAT                         14030
#define IDC_CUSTOMIZE_QAT               14040
#define IDC_RIBBONHELP                  14050
#define IDD_APPOINTMENT_DIALOG          16000
#define IDC_APP_CUST_INFO               16001
#define IDC_APP_PROP_INFO               16002
#define IDC_APP_DATE                    16003
#define IDC_APP_TIME                    16004
#define IDC_APP_TITLE                   16005
#define IDC_APP_DESC                    16006
#define IDC_APP_LOCATION                16007
#define IDC_APP_STATUS                  16008
#define IDC_BTN_APP_PRINT               16009
#define IDC_APP_CUST_ID                 16010
#define IDC_APP_PROP_ID                 16011
#define IDC_BTN_SELECT_PROP             16987
#define cmdTabTreeList                  20000
#define cmdTabTreeList_LabelTitle_RESID 20001
#define cmdTabListView                  20100
#define cmdTabListView_LabelTitle_RESID 20101
#define cmdGrpTreeOps                   21000
#define cmdGrpTreeOps_LabelTitle_RESID  21001
#define cmdGrpTreeMark                  21010
#define cmdGrpTreeMark_LabelTitle_RESID 21011
#define cmdGrpTreeStatus                21020
#define cmdGrpTreeStatus_LabelTitle_RESID 21021
#define cmdGrpTreeDocs                  21030
#define cmdGrpTreeDocs_LabelTitle_RESID 21031
#define cmdGrpTreeLayout                21040
#define cmdGrpTreeLayout_LabelTitle_RESID 21041
#define cmdGrpListRecord                22000
#define cmdGrpListRecord_LabelTitle_RESID 22001
#define cmdGrpListAdd                   22010
#define cmdGrpListAdd_LabelTitle_RESID  22011
#define cmdGrpListSet                   22020
#define cmdGrpListSet_LabelTitle_RESID  22021
#define cmdGrpListView                  22030
#define cmdGrpListView_LabelTitle_RESID 22031
#define cmdGrpListTools                 22040
#define cmdGrpListTools_LabelTitle_RESID 22041
#define cmdAppMenu                      23000
#define ID_TREELISTVIEWMENU_TEKLIFLERIG33000 23000
#define ID_MAINLISTVIEWMENU_SENKRONIZEET 23001
#define IDM_FILE_UPLOAD_CLOUD_PUSH      23002
#define ID_MAINLISTVIEWMENU_33003       23003
#define IDM_FLT_HEPSI                   23004
#define IDM_FLT_SICAK_ALICI             23005
#define IDM_FLT_SICAK_SATICI            23006
#define IDM_FLT_POT_ALICI               23007
#define IDM_FLT_POT_SATICI              23008
#define IDM_FLT_YATIRIMCI               23009
#define IDM_FLT_KIRACI                  23010
#define IDM_FLT_EV_SAHIBI               23011
#define IDM_FLT_YENI                    23012
#define IDM_FLT_TAKIP                   23013
#define IDM_FLT_RANDEVU                 23014
#define IDM_FLT_TEKLIF                  23015
#define IDM_FLT_TAMAMLANDI              23016
#define IDM_TREELIST_EDIT               24000
#define IDM_TREELIST_EDIT_LabelTitle_RESID 24001
#define IDM_TREELIST_VIEW               24010
#define IDM_TREELIST_VIEW_LabelTitle_RESID 24011
#define IDM_TREELIST_DELETE             24020
#define IDM_TREELIST_DELETE_LabelTitle_RESID 24021
#define IDM_TREELIST_SATILDI            24100
#define IDM_TREELIST_SATILDI_LabelTitle_RESID 24101
#define IDM_TREELIST_SATIS_DEVAM        24110
#define IDM_TREELIST_SATIS_DEVAM_LabelTitle_RESID 24111
#define IDM_TREELIST_WAIT               24120
#define IDM_TREELIST_WAIT_LabelTitle_RESID 24121
#define IDM_TREELIST_UNCERTAIN          24130
#define IDM_TREELIST_UNCERTAIN_LabelTitle_RESID 24131
#define IDM_STATUS_ACTIVE               24200
#define IDM_STATUS_ACTIVE_LabelTitle_RESID 24201
#define IDM_STATUS_SOLD                 24210
#define IDM_STATUS_SOLD_LabelTitle_RESID 24211
#define IDD_SAHI_IMPORT                 24218
#define IDM_STATUS_PRICE_DOWN           24220
#define IDM_STATUS_PRICE_DOWN_LabelTitle_RESID 24221
#define IDM_STATUS_URGENT               24230
#define IDM_STATUS_URGENT_LabelTitle_RESID 24231
#define IDM_STATUS_PASSIVE              24240
#define IDM_STATUS_PASSIVE_LabelTitle_RESID 24241
#define IDM_STATUS_SOLD_NEW             24250
#define IDM_STATUS_SOLD_NEW_LabelTitle_RESID 24251
#define IDM_STATUS_WAITING              24260
#define IDM_STATUS_WAITING_LabelTitle_RESID 24261
#define IDM_STATUS_PRICE_TRACKING       24270
#define IDM_STATUS_PRICE_TRACKING_LabelTitle_RESID 24271
#define IDM_STATUS_PROBLEMATIC          24280
#define IDM_STATUS_PROBLEMATIC_LabelTitle_RESID 24281
#define IDM_FONT_CHANGE                 24300
#define IDM_FONT_CHANGE_LabelTitle_RESID 24301
#define IDM_ONOFFER_MENU                24310
#define IDM_ONOFFER_MENU_LabelTitle_RESID 24311
#define IDM_VIEW_OFFERS                 24320
#define IDM_VIEW_OFFERS_LabelTitle_RESID 24321
#define IDM_SATILIK_YETKI               24330
#define IDM_SATILIK_YETKI_LabelTitle_RESID 24331
#define IDM_TREELIST_PREVIEW            24340
#define IDM_TREELIST_PREVIEW_LabelTitle_RESID 24341
#define IDM_KIRALIK_TEK_YETKI           24350
#define IDM_KIRALIK_TEK_YETKI_LabelTitle_RESID 24351
#define IDM_CAYMA_AKCESI                24360
#define IDM_CAYMA_AKCESI_LabelTitle_RESID 24361
#define IDM_KIRA_KONTRATOSU             24370
#define IDM_KIRA_KONTRATOSU_LabelTitle_RESID 24371
#define IDM_TEKLIF_FORMU                24380
#define IDM_TEKLIF_FORMU_LabelTitle_RESID 24381
#define IDM_YER_GOSTER                  24390
#define IDM_YER_GOSTER_LabelTitle_RESID 24391
#define IDM_ONALIM_FERAGAT              24400
#define IDM_ONALIM_FERAGAT_LabelTitle_RESID 24401
#define IDM_SAVECOLUMNWITH              24410
#define IDM_SAVECOLUMNWITH_LabelTitle_RESID 24411
#define ID_CONTEXT_EDIT_COLUMNS         24420
#define ID_CONTEXT_EDIT_COLUMNS_LabelTitle_RESID 24421
#define IDM_IMPORT_SAHIBINDEN           24500
#define IDM_NEW_RECORD                  25000
#define IDM_NEW_RECORD_LabelTitle_RESID 25001
#define IDM_RECORD_UPDATE               25010
#define IDM_RECORD_UPDATE_LabelTitle_RESID 25011
#define ID_MAINLISTVIEWMENU_KAYD32781   25020
#define ID_MAINLISTVIEWMENU_KAYD32781_LabelTitle_RESID 25021
#define IDM_DELETE_IS_SELECTED          25030
#define IDM_DELETE_IS_SELECTED_LabelTitle_RESID 25031
#define IDM_ADD_HOME                    25100
#define IDM_ADD_HOME_LabelTitle_RESID   25101
#define ID_EKLE_ARSA                    25110
#define ID_EKLE_ARSA_LabelTitle_RESID   25111
#define ID_EKLE_BAGVBAHCE               25120
#define ID_EKLE_BAGVBAHCE_LabelTitle_RESID 25121
#define ID_EKLE_TICARIALAN              25130
#define ID_EKLE_TICARIALAN_LabelTitle_RESID 25131
#define ID_EKLE_TARLA                   25140
#define ID_EKLE_TARLA_LabelTitle_RESID  25141
#define ID_EKLE_VILLA                   25150
#define ID_EKLE_VILLA_LabelTitle_RESID  25151
#define ID_EKLE_MUSTAKILHOME            25160
#define ID_EKLE_MUSTAKILHOME_LabelTitle_RESID 25161
#define IDM_ADD_CAR                     25175
#define IDM_SET_CALISIR                 25200
#define IDM_SET_CALISIR_LabelTitle_RESID 25201
#define IDM_SET_CALISMAZ                25210
#define IDM_SET_CALISMAZ_LabelTitle_RESID 25211
#define IDM_SET_DUSUNECEK               25220
#define IDM_SET_DUSUNECEK_LabelTitle_RESID 25221
#define ID_MAINLISTVIEWMENU_32793       25230
#define ID_MAINLISTVIEWMENU_32793_LabelTitle_RESID 25231
#define IDM_VIEW_CARD                   25300
#define IDM_VIEW_CARD_LabelTitle_RESID  25301
#define IDM_VIEW_REPORT                 25310
#define IDM_VIEW_REPORT_LabelTitle_RESID 25311
#define IDC_CMD_VIEW_DETAILS            25320
#define IDC_CMD_VIEW_DETAILS_LabelTitle_RESID 25321
#define IDC_CMD_VIEW_LIST               25330
#define IDC_CMD_VIEW_LIST_LabelTitle_RESID 25331
#define IDC_CMD_VIEW_SMALL              25340
#define IDC_CMD_VIEW_SMALL_LabelTitle_RESID 25341
#define IDM_SAVE_TO_DATABASE            25400
#define IDM_SAVE_TO_DATABASE_LabelTitle_RESID 25401
#define IDM_GOTOADRESS                  25410
#define IDM_GOTOADRESS_LabelTitle_RESID 25411
#define IDM_FILE_UPLOAD_CLOUD           25420
#define IDM_FILE_UPLOAD_CLOUD_LabelTitle_RESID 25421
#define IDM_GOOGLE_EXIT                 25430
#define IDM_GOOGLE_EXIT_LabelTitle_RESID 25431
#define IDM_RANDEVU_OLUSTUR             25440
#define IDM_RANDEVU_OLUSTUR_LabelTitle_RESID 25441
#define IDM_RANDEVU_GORUNTULE           25450
#define IDM_RANDEVU_GORUNTULE_LabelTitle_RESID 25451
#define IDM_OZELLIKLER                  25460
#define IDM_OZELLIKLER_LabelTitle_RESID 25461
#define ID_TREELISTVIEWMENU_T32839      32839
#define ID_TREELISTVIEWMENU_BASK32840   32840
#define ID_BASK32841                    32841
#define ID_TREELISTVIEWMENU_BASK32842   32842
#define ID_BASK32843                    32843
#define ID_MAINLISTVIEWMENU_GOOGLE32844 32844
#define ID_MAINLISTVIEWMENU_RANDEVUOLU32847 32847
#define ID_MAINLISTVIEWMENU_RANDEVUG32848 32848
#define ID_Menu                         32851
#define ID_MAINLISTVIEWMENU_FIRMABILGILERI 32853
#define IDM_COMPANY_INFO                32854
#define IDM_LISTVIEW_EDIT_CUSTOMER      32855
#define IDB_LISTVIEW                    33000
#define IDC_BROWSER_PLACEHOLDER         -32536
#define IDB_TREEVIEWICONS               33001
#define IDB_BITMAP33                    33002
#define IDB_MAINTOOLBAR                 33002
#define IDB_PNG8                        33003
#define IDR_PNG_CAR_EXPERTIZ_TEMPLATE   33003
#define ID_EKLE_ARABA                   33017
#define IDC_LAND_LISTING_TITLE   28720
#define IDC_LAND_LISTING_URL     28721
#define IDC_LV_VILLA_FACADES            42001
#define IDC_LV_VILLA_INT                42002
#define IDC_LV_VILLA_EXT                42003
#define IDC_LV_VILLA_NEIGHBOR           42004
#define IDC_LV_VILLA_TRANSPORT          42005
#define IDC_LV_VILLA_VIEW               42006
#define IDC_LV_VILLA_HOUSINGTYPE        42007
#define IDC_LV_VILLA_ACCESSIBILITY      42008

#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        33004
#define _APS_NEXT_COMMAND_VALUE         33018
#define _APS_NEXT_CONTROL_VALUE         33001
#define _APS_NEXT_SYMED_VALUE           33000
#endif
#endif


